// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfkqbyxmsrjljvpnosls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNma3FieXhtc3JqbGp2cG5vc2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTIzNzEsImV4cCI6MjA2MDk2ODM3MX0.yzs73geJmL_gcr1Ct3lK3yBLz7dlDvya1qzBz5qDg0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);